"""initial

Revision ID: f19af9f0a603
Revises: 
Create Date: 2022-03-18 20:55:46.073152

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f19af9f0a603"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("first_name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("last_name", sa.VARCHAR(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        "users_first_name",
        "users",
        ["first_name"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "users_first_name_last_name",
        "users",
        ["first_name", "last_name"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "users_last_name",
        "users",
        ["last_name"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_table(
        "emails",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("mail", sa.VARCHAR(length=320), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("mail"),
    )
    op.create_table(
        "phone_numbers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("number", sa.VARCHAR(length=22), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("number"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("phone_numbers")
    op.drop_table("emails")
    op.drop_index(
        "users_last_name", table_name="users", postgresql_using="btree"
    )
    op.drop_index(
        "users_first_name_last_name",
        table_name="users",
        postgresql_using="btree",
    )
    op.drop_index(
        "users_first_name", table_name="users", postgresql_using="btree"
    )
    op.drop_table("users")
    # ### end Alembic commands ###
